apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: coder-cluster
  region: us-west-2
vpc:
  cidr: 10.0.0.0/16
autoModeConfig:
  enabled: false
iam:
  withOIDC: true
addons:
- name: vpc-cni
  version: latest
  resolveConflicts: overwrite
  useDefaultPodIdentityAssociations: true
- name: kube-proxy
  version: latest
  resolveConflicts: overwrite
- name: coredns
  version: latest
  resolveConflicts: overwrite
- name: eks-pod-identity-agent
  version: latest
